name: Publish to NPM PRO

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - name: Set Gemfury Config
        run: printf "@iconscout:registry=https://npm-proxy.fury.io/iconscout/\n//npm-proxy.fury.io/iconscout/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.FURY_AUTH_TOKEN }}
      - name: Download & Build Icons
        run: |
          npm ci --progress=false
          npm i @iconscout/unicons@latest
          npm run generate
      - name: Publish to Gemfury
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FURY_AUTH_TOKEN }}
