name: Publish to NPM RC

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: 
      - 'release-*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push' 
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request' 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - name: Download & Build Icons
        run: npm ci --progress=false && npm i @iconscout/unicons@latest && npm run generate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          title: Updated Icons
      - name: Publish to NPM
        uses: primer/publish@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
