name: Publish to NPM

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          registry-url: "https://registry.npmjs.org"
      - name: Download & Build Icons
        run: npm ci --progress=false && npm i @iconscout/unicons@latest && npm run generate
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
